problems with mailer

diff --git a/shell_scripts/setup b/shell_scripts/setup
--- a/shell_scripts/setup
+++ b/shell_scripts/setup
@@ -1,7 +1,21 @@
 #!/bin/bash
+
+while getopts ":l:p:" opt; do
+  case $opt in
+    l) login="$OPTARG"
+    ;;
+    p) pwd="$OPTARG"
+    ;;
+    \?) echo "Invalid option -$OPTARG" >&2
+    ;;
+  esac
+done
+
 PROJECT_DIR="$(dirname "$0")"
 python3 -m venv $PROJECT_DIR/../.venv
 source $PROJECT_DIR/../.venv/bin/activate
 pip install --requirement $PROJECT_DIR/../api/requirements.txt
 
-source ./mongodb_setup
+bash $PROJECT_DIR/mongodb_setup.sh
+
+bash $PROJECT_DIR/init_ini.sh -l "$login" -p "$pwd"
